# Logo (Font Awesome Class)
#fa_logo: fa-quinscape
#fa_logo: fa-pencil-square
#fa_logo: fa-cuttlefish
fa_logo: fa-pagelines

# Header
menu:
  Home: /
  #Archives: /archives
  #About: /about.html
  #Tags: /tags
  #Categories: /categories
  #Contact: /contact.html

# Default post title
#default_post_title: Untitled
default_post_title: TTTT

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
#comments:
#  # Disqus comments
#  disqus_shortname:

# Google Analytics Tracking ID
# google_analytics:

# Social Accounts
#twitter_url: https://twitter.com/?lang=en
#facebook_url: https://www.facebook.com/
#instagram_url: https://www.instagram.com/
#dribble_url: https://dribbble.com/
#github_url: https://github.com/klugjo/hexo-theme-alpha-dust
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: info@nonlinear.capital
#rss_url: \#

# Footer About Text
#footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Nonlinear Capital. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

